### ISSUE TITLE
Update composer dependencies

### ISSUE THREAD

**Issue by Renegade334** [Renegade334/phergie-irc-plugin-react-usermode#3]
* phergie-irc-bot needs to be tagged to a version which includes `ircProtoctl` (@elazar)
* phergie-irc-parser needs to be tagged to a version which includes the MODE handling changes (@elazar)

Once depedencies available, update composer dependency files

**Comment by elazar** [comment]
bot 1.1.0 and parser 1.6.0 have been tagged with the changes referenced above.

**Comment by Renegade334** [comment]
The updated plugin would be dependent on commits made to the parser since 1.6.0, so it will have to wait for the next release (or a subrevision tag)

**Comment by elazar** [comment]
parser 1.6.1 has been released with the changes merged to master since 1.6.0.
